Numpy: Numerical python
1. NumPy provides efficient storage
2. It also provides better ways of handling data for processing
3. NumPy uses relatively less memory to store data

In [2]:
import numpy as np


#List vs NumPy array time taken

In [ ]:
from time import process_time

In [ ]:
my_list = [i for i in range(10000)]

start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time  - start_time)

0.001733592000000339


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)


0.0014862239999997584


#Creating an numpy array

In [ ]:
#list
list1 = [1,2,3,4,5]

print(list1)

type(list1)


[1, 2, 3, 4, 5]


list

In [21]:
#np array

np_array = np.array([1,2,3,4,5]) # one dimensional array
print(np_array)
type(np_array)
np_array.shape

np_array.size

5

In [23]:
#creating a multi-dimensional array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr[0].size



5

In [ ]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
arr2 = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)],dtype = float)
print(arr2)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


#Initial placeholder in numpy array

In [ ]:
#creating an array of zeros
x_array = np.zeros((4,5))
print(x_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating an array of equally distributed values : specifying the number of values  required
e_array= np.linspace(10,30,6)
print(e_array)

[10. 14. 18. 22. 26. 30.]


In [25]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
#creating an array of equally distributed values: specifying the gap
g_array = np.arange(10,30,6)
print(g_array)

[10 16 22 28]


In [27]:
rng = np.arange(16)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#creating an array of ones
y_array = np.ones((3,3))
print(y_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
#creating a empyt array
emp = np.empty((4,4))
emp

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323, 3.5e-323],
       [4.0e-323, 4.4e-323, 4.9e-323, 5.4e-323],
       [5.9e-323, 6.4e-323, 6.9e-323, 7.4e-323]])

In [ ]:
#creating an array of particular value
z_array = np.full((3,3),5)
print(z_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [30]:
 #creating an indentity matrix
i_array = np.identity(3)
print(i_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#axis in numpy array

In [33]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.sum(axis=0)

array([12, 15, 18])

In [34]:
arr.sum(axis=1)

array([ 6, 15, 24])

#iterator in numpy array


In [35]:
it =np.array([[1,2,3],[4,5,6],[7,8,9]])
it.flat
for i in it.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#creating a numpy with random varible
random_array = np.random.random((4,5))
print(random_array)
#value are between 0-1

[[0.6729028  0.66276008 0.21310892 0.86073061 0.53509803]
 [0.70958521 0.85748261 0.20874092 0.92008568 0.01129446]
 [0.04556607 0.96423629 0.47027693 0.92825067 0.75547254]
 [0.72698773 0.19423198 0.17383896 0.48340068 0.49603146]]


In [ ]:
 #creating an random  integer array with a specific range
rand_int = np.random.randint(10,100,(3,5))
print(rand_int)

[[22 84 44 93 63]
 [92 99 98 39 89]
 [79 65 97 65 10]]


In [ ]:
#converting a list into numpy array
list2 = [10,20,30,40,50]

np_arr = np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 30 40 50]


numpy.ndarray

#Analysis of numpy array

In [ ]:
nparr = np.random.randint(10,100,(5,5))
print(nparr)

[[89 12 54 53 83]
 [30 39 92 90 81]
 [93 25 20 10 23]
 [58 75 68 23 71]
 [73 22 52 72 58]]


In [ ]:
#array dimension
nparr.shape

(5, 5)

In [ ]:
#number of dimension
nparr.ndim

2

In [ ]:
# number of element in an array
print(nparr.size)

25


In [ ]:
#checking the type of element of array
print(nparr.dtype)

int64


#Opeation on an array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2) # concatination of list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# for numpy array

r_arr1 = np.random.randint(0,10,(3,3))
r_arr2 = np.random.randint(10,20,(3,3))

print(r_arr1)
print(r_arr2)

[[8 5 2]
 [6 2 2]
 [2 5 7]]
[[18 13 15]
 [10 15 10]
 [12 15 19]]


In [ ]:
print(r_arr1+r_arr2)
print(r_arr1-r_arr2)
print(r_arr1*r_arr2)
print(r_arr1/r_arr2)




[[26 18 17]
 [16 17 12]
 [14 20 26]]
[[-10  -8 -13]
 [ -4 -13  -8]
 [-10 -10 -12]]
[[144  65  30]
 [ 60  30  20]
 [ 24  75 133]]
[[0.44444444 0.38461538 0.13333333]
 [0.6        0.13333333 0.2       ]
 [0.16666667 0.33333333 0.36842105]]


In [ ]:
r_arr1 = np.random.randint(0,10,(3,3))
r_arr2 = np.random.randint(10,20,(3,3))

print(r_arr1)
print(r_arr2)

[[4 9 3]
 [1 2 6]
 [5 6 6]]
[[11 19 16]
 [16 12 17]
 [16 19 16]]


In [ ]:
#another way of doing same thing
print(np.add(r_arr1,r_arr2))
print(np.subtract(r_arr1,r_arr2))
print(np.multiply(r_arr1,r_arr2))
print(np.divide(r_arr1,r_arr2))

[[15 28 19]
 [17 14 23]
 [21 25 22]]
[[ -7 -10 -13]
 [-15 -10 -11]
 [-11 -13 -10]]
[[ 44 171  48]
 [ 16  24 102]
 [ 80 114  96]]
[[0.36363636 0.47368421 0.1875    ]
 [0.0625     0.16666667 0.35294118]
 [0.3125     0.31578947 0.375     ]]


#Array Manipluation

In [ ]:
arr_manu = np.random.randint(10,20,(3,3));
print(arr_manu)
print(arr_manu.shape)

[[19 13 17]
 [12 15 18]
 [11 15 16]]
(3, 3)


In [ ]:
#transpose of array
arr_manu2= np.transpose(arr_manu)
print(arr_manu2)

[[19 12 11]
 [13 15 15]
 [17 18 16]]


In [ ]:
trans = arr_manu.T
print(trans)

[[19 12 11]
 [13 15 15]
 [17 18 16]]


In [ ]:
#reshaping of array
reshape_arr = np.random.randint(10,20,(2,3));
print(reshape_arr)
print(reshape_arr.shape)

[[18 17 15]
 [19 16 19]]
(2, 3)


In [ ]:
a = reshape_arr.reshape(3,2)
print(a)
print(a.shape)

[[18 17]
 [15 19]
 [16 19]]
(3, 2)
